-- OLT Control core schema
-- Mirrors the Supabase migrations applied on 2026-10-08.

create table if not exists public.sap_cargas (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  usuario_id uuid null references auth.users(id),
  archivo text,
  total_filas integer not null default 0,
  referencias_unicas integer not null default 0,
  referencias_nuevas integer not null default 0,
  referencias_actualizadas integer not null default 0,
  estado text not null default 'pendiente' check (estado in ('pendiente','validando','publicada','rechazada')),
  mensaje text,
  publicada_at timestamptz
);

create table if not exists public.sap_staging (
  id bigint generated by default as identity primary key,
  carga_id bigint not null references public.sap_cargas(id) on delete cascade,
  fila_origen integer,
  referencia text,
  inacttrans timestamptz,
  dt text,
  et text,
  placa text,
  fecha_salida_sap timestamptz,
  estado_viaje text,
  estado_entrega text,
  fec_reg date,
  hor_reg time,
  usua_ctrl_re text,
  raw_data jsonb not null default '{}'::jsonb
);

create table if not exists public.sap_actual (
  referencia text primary key,
  inacttrans timestamptz,
  dt text,
  et text,
  placa text,
  fecha_salida_sap timestamptz,
  estado_viaje text,
  estado_entrega text,
  fec_reg date,
  hor_reg time,
  usua_ctrl_re text,
  raw_data jsonb not null default '{}'::jsonb,
  carga_id bigint references public.sap_cargas(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.sap_historial (
  id bigint generated by default as identity primary key,
  referencia text not null,
  inacttrans timestamptz,
  dt text,
  et text,
  placa text,
  fecha_salida_sap timestamptz,
  estado_viaje text,
  estado_entrega text,
  fec_reg date,
  hor_reg time,
  usua_ctrl_re text,
  raw_data jsonb not null default '{}'::jsonb,
  carga_id bigint references public.sap_cargas(id),
  registrado_at timestamptz not null default now(),
  motivo_cambio text
);

create table if not exists public.gestion_olt (
  olt_id bigint primary key references public.recepcion_olt(id) on delete cascade,
  nro_cargo text,
  fec_cargo date,
  codigo_transporte text,
  placa_prog text,
  dt_prog text,
  transporte_prog text,
  responsable text,
  motivo text,
  updated_at timestamptz not null default now(),
  updated_by uuid null references auth.users(id)
);

create table if not exists public.cierre_mensual (
  id bigint generated by default as identity primary key,
  periodo date not null,
  olt_id bigint not null references public.recepcion_olt(id),
  entrega text,
  snapshot jsonb not null,
  cerrado_at timestamptz not null default now(),
  cerrado_por uuid null references auth.users(id),
  unique(periodo, olt_id),
  check (date_trunc('month', periodo)::date = periodo)
);

create index if not exists sap_staging_carga_idx on public.sap_staging(carga_id);
create index if not exists sap_staging_ref_inact_idx on public.sap_staging(referencia, inacttrans desc);
create index if not exists sap_actual_inact_idx on public.sap_actual(inacttrans desc);
create index if not exists sap_historial_ref_idx on public.sap_historial(referencia, registrado_at desc);
create index if not exists cierre_mensual_periodo_idx on public.cierre_mensual(periodo);

create index if not exists sap_cargas_usuario_id_idx on public.sap_cargas(usuario_id);
create index if not exists sap_actual_carga_id_idx on public.sap_actual(carga_id);
create index if not exists sap_historial_carga_id_idx on public.sap_historial(carga_id);
create index if not exists gestion_olt_updated_by_idx on public.gestion_olt(updated_by);
create index if not exists cierre_mensual_olt_id_idx on public.cierre_mensual(olt_id);
create index if not exists cierre_mensual_cerrado_por_idx on public.cierre_mensual(cerrado_por);

alter table public.sap_cargas enable row level security;
alter table public.sap_staging enable row level security;
alter table public.sap_actual enable row level security;
alter table public.sap_historial enable row level security;
alter table public.gestion_olt enable row level security;
alter table public.cierre_mensual enable row level security;

-- Policies are intentionally not created yet.
-- Access will remain closed until the final user roles are defined.
